import type { ComplianceRecord, ComplianceOverviewItem } from "@/types";

export const complianceRecords: ComplianceRecord[] = [
  {
    id: "com-001",
    operatorName: "MTN Rwanda Ltd",
    licenseId: "lic-001",
    sector: "Telecom",
    checkType: "Quality of Service (QoS) Audit",
    status: "compliant",
    dueDate: "2026-03-31",
    lastAuditDate: "2026-01-20",
    score: 91,
    auditor: "Jean-Claude Ndayisaba",
  },
  {
    id: "com-002",
    operatorName: "Airtel Rwanda Ltd",
    licenseId: "lic-002",
    sector: "Telecom",
    checkType: "Annual Return Filing",
    status: "under_review",
    dueDate: "2026-04-15",
    lastAuditDate: "2026-02-28",
    score: 74,
    auditor: "Amina Uwimana",
    findings: "Financial statements submitted late; prior-year restatement required.",
  },
  {
    id: "com-003",
    operatorName: "Ruzizi Thermal Power Ltd",
    licenseId: "lic-009",
    sector: "Energy",
    checkType: "Environmental Compliance",
    status: "non_compliant",
    dueDate: "2026-02-28",
    lastAuditDate: "2025-11-10",
    score: 38,
    auditor: "Jeannette Umurerwa",
    findings: "Emissions exceeded permissible threshold for 3 consecutive quarters. Remediation plan not submitted.",
  },
  {
    id: "com-004",
    operatorName: "Rwanda Energy Group (EUCL)",
    licenseId: "lic-007",
    sector: "Energy",
    checkType: "Network Rollout Target",
    status: "remediation",
    dueDate: "2026-04-01",
    lastAuditDate: "2026-03-01",
    score: 62,
    auditor: "Jean-Claude Ndayisaba",
    findings: "Rural electrification target at 68% against 80% commitment. Remediation plan accepted; quarterly reviews required.",
  },
  {
    id: "com-005",
    operatorName: "WASAC – Water & Sanitation Corp.",
    licenseId: "lic-010",
    sector: "Water",
    checkType: "Consumer Protection Audit",
    status: "compliant",
    dueDate: "2026-03-31",
    lastAuditDate: "2026-02-15",
    score: 88,
    auditor: "Amina Uwimana",
  },
  {
    id: "com-006",
    operatorName: "Liquid Intelligent Technologies Rwanda",
    licenseId: "lic-003",
    sector: "Telecom",
    checkType: "Quality of Service (QoS) Audit",
    status: "compliant",
    dueDate: "2026-04-30",
    lastAuditDate: "2026-02-10",
    score: 82,
    auditor: "Jean-Claude Ndayisaba",
  },
  {
    id: "com-007",
    operatorName: "Terracom Rwanda",
    licenseId: "lic-006",
    sector: "Telecom",
    checkType: "Annual Return Filing",
    status: "compliant",
    dueDate: "2026-04-30",
    lastAuditDate: "2026-03-05",
    score: 79,
    auditor: "Amina Uwimana",
  },
  {
    id: "com-008",
    operatorName: "Volcano Express Ltd",
    licenseId: "lic-011",
    sector: "Transport",
    checkType: "Consumer Protection Audit",
    status: "under_review",
    dueDate: "2026-03-15",
    lastAuditDate: "2026-02-20",
    score: 67,
    auditor: "Jeannette Umurerwa",
    findings: "Passenger injury reporting procedures not documented. Staff training records incomplete.",
  },
  {
    id: "com-009",
    operatorName: "Capital Express Transport",
    licenseId: "lic-012",
    sector: "Transport",
    checkType: "Consumer Protection Audit",
    status: "non_compliant",
    dueDate: "2026-03-10",
    lastAuditDate: "2025-12-15",
    score: 41,
    auditor: "Jeannette Umurerwa",
    findings: "Three substantiated tariff overcharge complaints unresolved. Complaint register absent. Consumer charter not displayed at terminals.",
  },
  {
    id: "com-010",
    operatorName: "EDCL – Energy Development Corp.",
    licenseId: "lic-008",
    sector: "Energy",
    checkType: "Financial Reporting",
    status: "compliant",
    dueDate: "2026-04-15",
    lastAuditDate: "2026-03-12",
    score: 87,
    auditor: "Jean-Claude Ndayisaba",
  },
];

export const complianceOverview: ComplianceOverviewItem[] = [
  { name: "Compliant",     value: 54, color: "#10B981" },
  { name: "Under Review",  value: 22, color: "#F59E0B" },
  { name: "Non-Compliant", value: 16, color: "#EF4444" },
  { name: "Remediation",   value: 8,  color: "#6366f1" },
];
