import type { Complaint, ComplaintsBySectorPoint } from "@/types";

// 12 Rwanda-relevant consumer complaints across Telecom, Energy, Water, Transport
export const complaints: Complaint[] = [
  {
    id: "cmp-001",
    referenceNumber: "RURA-CMP-2026-0041",
    subject: "Persistent 4G network outage in Musanze district",
    category: "Service Interruption",
    complainantName: "Théophile Nkurunziza",
    complainantPhone: "+250788123456",
    respondentOperator: "MTN Rwanda Ltd",
    sector: "Telecom",
    province: "Northern Province",
    status: "under_review",
    severity: "high",
    filedAt: "2026-03-10",
    updatedAt: "2026-03-18",
    assignedTo: "Amina Uwimana",
    description:
      "Customer reports complete loss of 4G connectivity in Musanze for 5 consecutive days. Business operations severely affected. Operator has not provided a restoration timeline.",
  },
  {
    id: "cmp-002",
    referenceNumber: "RURA-CMP-2026-0039",
    subject: "Unauthorised data bundle charges on prepaid account",
    category: "Unauthorized Charges",
    complainantName: "Josiane Mukagasana",
    complainantPhone: "+250722456789",
    respondentOperator: "Airtel Rwanda Ltd",
    sector: "Telecom",
    province: "Kigali City",
    status: "open",
    severity: "medium",
    filedAt: "2026-03-08",
    updatedAt: "2026-03-08",
    description:
      "RWF 15,000 deducted without consent for auto-renewed data bundle. Customer had not opted in to auto-renewal. Refund request declined by operator.",
  },
  {
    id: "cmp-003",
    referenceNumber: "RURA-CMP-2026-0035",
    subject: "Electricity supply interrupted for 72 hours — Nyabihu sector",
    category: "Service Interruption",
    complainantName: "Celestin Havugimana",
    complainantPhone: "+250788234567",
    respondentOperator: "Rwanda Energy Group (EUCL)",
    sector: "Energy",
    province: "Western Province",
    status: "escalated",
    severity: "critical",
    filedAt: "2026-02-28",
    updatedAt: "2026-03-15",
    assignedTo: "Jean-Claude Ndayisaba",
    description:
      "A transformer fault caused a 72-hour blackout affecting 400+ households. EUCL did not communicate the outage. Perishable goods destroyed. Compensation sought.",
  },
  {
    id: "cmp-004",
    referenceNumber: "RURA-CMP-2026-0033",
    subject: "Monthly electricity bill 300% higher than usual",
    category: "Billing Dispute",
    complainantName: "Régine Uwase",
    complainantPhone: "+250722345678",
    respondentOperator: "Rwanda Energy Group (EUCL)",
    sector: "Energy",
    province: "Southern Province",
    status: "under_review",
    severity: "high",
    filedAt: "2026-02-25",
    updatedAt: "2026-03-10",
    assignedTo: "Amina Uwimana",
    description:
      "Customer received an electricity bill of RWF 320,000 against a typical monthly bill of RWF 80,000. Meter appears to have been misread. Operator refusing to investigate.",
  },
  {
    id: "cmp-005",
    referenceNumber: "RURA-CMP-2026-0030",
    subject: "No tap water supply for 10 days in Gicumbi",
    category: "Service Interruption",
    complainantName: "Françoise Nyirahabimana",
    complainantPhone: "+250788567890",
    respondentOperator: "WASAC – Water & Sanitation Corp.",
    sector: "Water",
    province: "Northern Province",
    status: "resolved",
    severity: "critical",
    filedAt: "2026-02-14",
    updatedAt: "2026-03-05",
    resolvedAt: "2026-03-05",
    description:
      "Pipe rupture near Gicumbi town centre left 600 households without water for 10 days. WASAC restored supply after RURA intervention but has not provided compensation.",
  },
  {
    id: "cmp-006",
    referenceNumber: "RURA-CMP-2026-0027",
    subject: "Internet speed consistently below contracted 10 Mbps",
    category: "Poor Quality of Service",
    complainantName: "Olivier Nshimiyimana",
    complainantPhone: "+250722678901",
    respondentOperator: "Liquid Intelligent Technologies Rwanda",
    sector: "Telecom",
    province: "Kigali City",
    status: "open",
    severity: "medium",
    filedAt: "2026-02-05",
    updatedAt: "2026-02-05",
    description:
      "Business fibre line contracted at 10 Mbps. Speed tests consistently show 1.2–2.4 Mbps. Operator conducted no investigation despite three support tickets over 60 days.",
  },
  {
    id: "cmp-007",
    referenceNumber: "RURA-CMP-2026-0025",
    subject: "New electricity connection delayed beyond 90-day SLA",
    category: "Connection Delay",
    complainantName: "Epiphanie Mukamwiza",
    complainantPhone: "+250788456789",
    respondentOperator: "Rwanda Energy Group (EUCL)",
    sector: "Energy",
    province: "Eastern Province",
    status: "under_review",
    severity: "medium",
    filedAt: "2026-01-30",
    updatedAt: "2026-02-20",
    assignedTo: "Jean-Claude Ndayisaba",
    description:
      "Application for new electricity connection submitted in October 2025. Full payment made. 150 days have elapsed; connection still not installed. EUCL has not communicated a schedule.",
  },
  {
    id: "cmp-008",
    referenceNumber: "RURA-CMP-2026-0022",
    subject: "Bus operator charging above regulated tariff",
    category: "Tariff Overcharge",
    complainantName: "Pacifique Uwimana",
    complainantPhone: "+250722789012",
    respondentOperator: "Volcano Express Ltd",
    sector: "Transport",
    province: "Southern Province",
    status: "open",
    severity: "low",
    filedAt: "2026-01-22",
    updatedAt: "2026-01-22",
    description:
      "Kigali–Butare route fare charged at RWF 3,500 against the RURA-regulated maximum of RWF 2,800. Operator refused to display official tariff schedule.",
  },
  {
    id: "cmp-009",
    referenceNumber: "RURA-CMP-2026-0018",
    subject: "SIM card registered without customer's consent",
    category: "Data Privacy Breach",
    complainantName: "Jeanne d'Arc Ingabire",
    complainantPhone: "+250788890123",
    respondentOperator: "MTN Rwanda Ltd",
    sector: "Telecom",
    province: "Kigali City",
    status: "escalated",
    severity: "critical",
    filedAt: "2026-01-15",
    updatedAt: "2026-03-01",
    assignedTo: "Amina Uwimana",
    description:
      "Complainant discovered two SIM cards registered under their National ID without knowledge or consent. Potential identity theft. Operator's investigation inconclusive after 45 days.",
  },
  {
    id: "cmp-010",
    referenceNumber: "RURA-CMP-2025-0189",
    subject: "Water meter reading disputed — overcharged for 6 months",
    category: "Billing Dispute",
    complainantName: "Théodore Semana",
    complainantPhone: "+250722901234",
    respondentOperator: "WASAC – Water & Sanitation Corp.",
    sector: "Water",
    province: "Kigali City",
    status: "resolved",
    severity: "medium",
    filedAt: "2025-11-10",
    updatedAt: "2026-01-08",
    resolvedAt: "2026-01-08",
    description:
      "Faulty water meter caused inflated readings for 6 months. Total overcharge of RWF 180,000. WASAC eventually replaced meter and issued partial credit after RURA referral.",
  },
  {
    id: "cmp-011",
    referenceNumber: "RURA-CMP-2025-0175",
    subject: "Call centre unresponsive for 30 days after service disruption",
    category: "Customer Service Failure",
    complainantName: "Alice Mukamusoni",
    complainantPhone: "+250788012345",
    respondentOperator: "Airtel Rwanda Ltd",
    sector: "Telecom",
    province: "Eastern Province",
    status: "closed",
    severity: "low",
    filedAt: "2025-10-20",
    updatedAt: "2025-11-30",
    resolvedAt: "2025-11-30",
    description:
      "Service disruption reported; operator call centre failed to follow up for 30 days. Issue eventually resolved but operator did not apologise or offer goodwill gesture.",
  },
  {
    id: "cmp-012",
    referenceNumber: "RURA-CMP-2025-0160",
    subject: "Freight goods damaged due to carrier negligence",
    category: "Contract Violation",
    complainantName: "Venuste Rurangwa",
    complainantPhone: "+250722123456",
    respondentOperator: "Capital Express Transport",
    sector: "Transport",
    province: "Eastern Province",
    status: "closed",
    severity: "high",
    filedAt: "2025-09-15",
    updatedAt: "2025-12-10",
    resolvedAt: "2025-12-10",
    description:
      "Agricultural goods valued at RWF 4.2 million damaged during transit. Evidence of improper loading. Carrier accepted partial liability and compensated RWF 2.1 million.",
  },
];

export const complaintsBySector: ComplaintsBySectorPoint[] = [
  { sector: "Telecom", count: 218 },
  { sector: "Energy",  count: 174 },
  { sector: "Water",   count: 96  },
  { sector: "Transport", count: 42 },
];
