import type { Alert } from "@/types";

export const alerts: Alert[] = [
  {
    id: "alt-001",
    type: "license_expiry",
    title: "Licence Expiring Soon",
    message: "Airtel Rwanda Ltd ISP licence expires in 9 days (2026-04-01). Renewal not yet initiated.",
    severity: "critical",
    status: "unread",
    relatedModule: "Licenses",
    relatedEntityId: "lic-002",
    createdAt: "2026-03-22T06:00:00Z",
  },
  {
    id: "alt-002",
    type: "fraud_detected",
    title: "New Critical Fraud Case",
    message: "Spectrum interference case RURA-FRD-2026-0022 flagged as critical — requires immediate assignment.",
    severity: "critical",
    status: "unread",
    relatedModule: "Fraud",
    relatedEntityId: "frd-007",
    createdAt: "2026-03-21T17:00:00Z",
  },
  {
    id: "alt-003",
    type: "compliance_breach",
    title: "Compliance Deadline Overdue",
    message: "Capital Express Transport — Consumer Protection Audit was due 2026-03-10 and remains non-compliant.",
    severity: "critical",
    status: "unread",
    relatedModule: "Compliance",
    relatedEntityId: "com-009",
    createdAt: "2026-03-11T08:00:00Z",
  },
  {
    id: "alt-004",
    type: "complaint_sla_breach",
    title: "SLA Breach — Complaint Unresolved",
    message: "Complaint CMP-2026-0009 has been open for 18 days with no assignee. SLA threshold: 14 days.",
    severity: "warning",
    status: "read",
    relatedModule: "Complaints",
    relatedEntityId: "cmp-009",
    createdAt: "2026-03-20T09:00:00Z",
    readAt: "2026-03-20T10:15:00Z",
  },
  {
    id: "alt-005",
    type: "workflow_stalled",
    title: "Workflow Stalled",
    message: "Licence Renewal Workflow for WASAC (wfl-004) has been paused for 5 days with no progress.",
    severity: "warning",
    status: "unread",
    relatedModule: "Workflows",
    relatedEntityId: "wfl-004",
    createdAt: "2026-03-20T07:30:00Z",
  },
  {
    id: "alt-006",
    type: "threshold_exceeded",
    title: "Fraud Loss Threshold Exceeded",
    message: "Estimated losses on active fraud cases have exceeded RWF 200,000,000 this quarter.",
    severity: "critical",
    status: "actioned",
    relatedModule: "Fraud",
    createdAt: "2026-03-19T12:00:00Z",
    actionedBy: "Kagiso Mutabazi",
  },
  {
    id: "alt-007",
    type: "report_ready",
    title: "Report Published",
    message: "Q4 2025 Telecom Sector Regulatory Report has been published and is available for download.",
    severity: "info",
    status: "read",
    relatedModule: "Reports",
    relatedEntityId: "rpt-003",
    createdAt: "2026-03-18T16:00:00Z",
    readAt: "2026-03-18T16:45:00Z",
  },
  {
    id: "alt-008",
    type: "license_expiry",
    title: "Licence Expiring — 30 Days",
    message: "Terracom Rwanda Broadcasting licence expires 2026-04-30. Renewal should be initiated.",
    severity: "warning",
    status: "dismissed",
    relatedModule: "Licenses",
    relatedEntityId: "lic-006",
    createdAt: "2026-03-17T08:00:00Z",
  },
  {
    id: "alt-009",
    type: "user_suspended",
    title: "User Account Suspended",
    message: "User account for Solange Nyiransabimana (Licensing Supervisor) was suspended pending review.",
    severity: "warning",
    status: "read",
    relatedModule: "Users",
    relatedEntityId: "usr-008",
    createdAt: "2026-03-15T10:00:00Z",
    readAt: "2026-03-15T10:30:00Z",
  },
  {
    id: "alt-010",
    type: "system_error",
    title: "System Sync Error",
    message: "CLMS document sync failed for 3 cases between 02:00–03:00 UTC. Manual re-sync required.",
    severity: "info",
    status: "actioned",
    relatedModule: "CLMS",
    createdAt: "2026-03-14T03:05:00Z",
    actionedBy: "Kagiso Mutabazi",
  },
];
