import type { CLMSCase } from "@/types";

export const clmsCases: CLMSCase[] = [
  {
    id: "cls-001",
    caseNumber: "CLMS-2026-0041",
    title: "New Mobile Network Operator Licence — TeleCom Solutions Ltd",
    type: "new_license",
    status: "under_review",
    applicantName: "TeleCom Solutions Ltd",
    applicantEmail: "licensing@telecomsolutions.rw",
    sector: "Telecom",
    province: "Kigali City",
    submittedAt: "2026-03-08",
    updatedAt: "2026-03-15",
    assignedTo: "Jeannette Umurerwa",
    documents: [
      { id: "doc-001a", name: "Certificate of Incorporation.pdf", uploadedAt: "2026-03-08", uploadedBy: "TeleCom Solutions Ltd", sizeKb: 420 },
      { id: "doc-001b", name: "Technical Proposal.pdf", uploadedAt: "2026-03-08", uploadedBy: "TeleCom Solutions Ltd", sizeKb: 2840 },
      { id: "doc-001c", name: "Financial Statements 2025.xlsx", uploadedAt: "2026-03-10", uploadedBy: "TeleCom Solutions Ltd", sizeKb: 1150 },
    ],
    notes: "Applicant has requested expedited review. Technical proposal is under assessment by ICT team.",
  },
  {
    id: "cls-002",
    caseNumber: "CLMS-2026-0038",
    title: "Licence Renewal — Airtel Rwanda Ltd ISP Licence",
    type: "license_renewal",
    status: "submitted",
    applicantName: "Airtel Rwanda Ltd",
    applicantEmail: "regulatory@airtel.rw",
    sector: "Telecom",
    province: "Kigali City",
    submittedAt: "2026-03-12",
    updatedAt: "2026-03-12",
    assignedTo: "Olivier Hakizimana",
    documents: [
      { id: "doc-002a", name: "Renewal Application Form.pdf", uploadedAt: "2026-03-12", uploadedBy: "Airtel Rwanda Ltd", sizeKb: 380 },
      { id: "doc-002b", name: "Compliance Certificate 2025.pdf", uploadedAt: "2026-03-12", uploadedBy: "Airtel Rwanda Ltd", sizeKb: 210 },
    ],
  },
  {
    id: "cls-003",
    caseNumber: "CLMS-2026-0035",
    title: "Tariff Review — WASAC Water Supply Tariff Revision",
    type: "tariff_review",
    status: "approved",
    applicantName: "WASAC – Water & Sanitation Corp.",
    applicantEmail: "tariffs@wasac.rw",
    sector: "Water",
    province: "Kigali City",
    submittedAt: "2026-02-10",
    updatedAt: "2026-03-18",
    assignedTo: "Amina Uwimana",
    documents: [
      { id: "doc-003a", name: "Tariff Review Application.pdf", uploadedAt: "2026-02-10", uploadedBy: "WASAC", sizeKb: 1240 },
      { id: "doc-003b", name: "Cost Model 2026.xlsx", uploadedAt: "2026-02-10", uploadedBy: "WASAC", sizeKb: 3200 },
      { id: "doc-003c", name: "Public Consultation Summary.pdf", uploadedAt: "2026-03-01", uploadedBy: "RURA Analyst", sizeKb: 870 },
      { id: "doc-003d", name: "Approval Notice.pdf", uploadedAt: "2026-03-18", uploadedBy: "Kagiso Mutabazi", sizeKb: 185 },
    ],
    notes: "Tariff increase of 8% approved effective 1 May 2026. Operator notified via formal notice.",
  },
  {
    id: "cls-004",
    caseNumber: "CLMS-2026-0029",
    title: "Spectrum Assignment — MTN Rwanda 700 MHz Band",
    type: "spectrum_assignment",
    status: "under_review",
    applicantName: "MTN Rwanda Ltd",
    applicantEmail: "spectrum@mtn.rw",
    sector: "Telecom",
    province: "Kigali City",
    submittedAt: "2026-02-18",
    updatedAt: "2026-03-10",
    assignedTo: "Kagiso Mutabazi",
    documents: [
      { id: "doc-004a", name: "Spectrum Request Form.pdf", uploadedAt: "2026-02-18", uploadedBy: "MTN Rwanda Ltd", sizeKb: 560 },
      { id: "doc-004b", name: "Interference Analysis Report.pdf", uploadedAt: "2026-02-22", uploadedBy: "MTN Rwanda Ltd", sizeKb: 4100 },
    ],
    notes: "Awaiting technical review from ICT department. Coordination with telecoms neighbours in progress.",
  },
  {
    id: "cls-005",
    caseNumber: "CLMS-2026-0031",
    title: "Tariff Review — Terracom Rwanda Voice Tariff",
    type: "tariff_review",
    status: "rejected",
    applicantName: "Terracom Rwanda",
    applicantEmail: "regulatory@terracom.rw",
    sector: "Telecom",
    province: "Northern Province",
    submittedAt: "2026-02-05",
    updatedAt: "2026-03-20",
    assignedTo: "Amina Uwimana",
    documents: [
      { id: "doc-005a", name: "Tariff Review Application.pdf", uploadedAt: "2026-02-05", uploadedBy: "Terracom Rwanda", sizeKb: 780 },
      { id: "doc-005b", name: "Rejection Notice.pdf", uploadedAt: "2026-03-20", uploadedBy: "Amina Uwimana", sizeKb: 155 },
    ],
    notes: "Application rejected — proposed tariffs exceed regulatory ceiling. Operator may resubmit with revised figures.",
  },
  {
    id: "cls-006",
    caseNumber: "CLMS-2025-0112",
    title: "Type Approval — Huawei Router Series H5X",
    type: "type_approval",
    status: "approved",
    applicantName: "Liquid Intelligent Technologies Rwanda",
    applicantEmail: "technical@liquid.rw",
    sector: "Telecom",
    province: "Kigali City",
    submittedAt: "2025-11-15",
    updatedAt: "2025-12-20",
    assignedTo: "Olivier Hakizimana",
    documents: [
      { id: "doc-006a", name: "Device Specification Sheet.pdf", uploadedAt: "2025-11-15", uploadedBy: "Liquid Rwanda", sizeKb: 2200 },
      { id: "doc-006b", name: "EMC Test Report.pdf", uploadedAt: "2025-11-15", uploadedBy: "Liquid Rwanda", sizeKb: 1850 },
      { id: "doc-006c", name: "Type Approval Certificate.pdf", uploadedAt: "2025-12-20", uploadedBy: "Kagiso Mutabazi", sizeKb: 220 },
    ],
  },
  {
    id: "cls-007",
    caseNumber: "CLMS-2026-0044",
    title: "Licence Amendment — EDCL Generation Capacity Expansion",
    type: "license_amendment",
    status: "draft",
    applicantName: "EDCL – Energy Development Corp.",
    applicantEmail: "licensing@edcl.rw",
    sector: "Energy",
    province: "Southern Province",
    submittedAt: "2026-03-20",
    updatedAt: "2026-03-20",
    assignedTo: "Jean-Claude Ndayisaba",
    documents: [
      { id: "doc-007a", name: "Amendment Request.pdf", uploadedAt: "2026-03-20", uploadedBy: "EDCL", sizeKb: 495 },
    ],
    notes: "Draft — pending internal sign-off before formal submission to RURA.",
  },
  {
    id: "cls-008",
    caseNumber: "CLMS-2026-0022",
    title: "Dispute Resolution — Volcano Express vs RURA Tariff Order",
    type: "dispute_resolution",
    status: "appealed",
    applicantName: "Volcano Express Ltd",
    applicantEmail: "legal@volcanoexpress.rw",
    sector: "Transport",
    province: "Western Province",
    submittedAt: "2026-01-28",
    updatedAt: "2026-03-05",
    assignedTo: "Amina Uwimana",
    documents: [
      { id: "doc-008a", name: "Appeal Submission.pdf", uploadedAt: "2026-01-28", uploadedBy: "Volcano Express Ltd", sizeKb: 1620 },
      { id: "doc-008b", name: "RURA Decision Notice.pdf", uploadedAt: "2026-02-20", uploadedBy: "Kagiso Mutabazi", sizeKb: 340 },
      { id: "doc-008c", name: "Counter-submission.pdf", uploadedAt: "2026-03-05", uploadedBy: "Volcano Express Ltd", sizeKb: 980 },
    ],
    notes: "Operator has appealed the initial RURA tariff order. Case referred to Regulatory Appeals Committee.",
  },
  {
    id: "cls-009",
    caseNumber: "CLMS-2025-0098",
    title: "Licence Revocation — Ruzizi Thermal Power Environmental Breach",
    type: "license_revocation",
    status: "closed",
    applicantName: "Ruzizi Thermal Power Ltd",
    applicantEmail: "admin@ruzizi.rw",
    sector: "Energy",
    province: "Western Province",
    submittedAt: "2025-10-01",
    updatedAt: "2026-02-15",
    assignedTo: "Jean-Claude Ndayisaba",
    documents: [
      { id: "doc-009a", name: "Show Cause Notice.pdf", uploadedAt: "2025-10-01", uploadedBy: "RURA", sizeKb: 280 },
      { id: "doc-009b", name: "Operator Response.pdf", uploadedAt: "2025-10-20", uploadedBy: "Ruzizi Thermal Power", sizeKb: 1100 },
      { id: "doc-009c", name: "Final Revocation Order.pdf", uploadedAt: "2026-02-15", uploadedBy: "Kagiso Mutabazi", sizeKb: 310 },
    ],
    notes: "Licence revocation proceeding concluded. Remediation plan rejected. Formal revocation order issued.",
  },
  {
    id: "cls-010",
    caseNumber: "CLMS-2026-0046",
    title: "New Road Transport Operator Licence — Kigali Star Bus",
    type: "new_license",
    status: "submitted",
    applicantName: "Kigali Star Bus Ltd",
    applicantEmail: "compliance@kigalistarbus.rw",
    sector: "Transport",
    province: "Kigali City",
    submittedAt: "2026-03-21",
    updatedAt: "2026-03-21",
    assignedTo: "Jeannette Umurerwa",
    documents: [
      { id: "doc-010a", name: "Application Form.pdf", uploadedAt: "2026-03-21", uploadedBy: "Kigali Star Bus Ltd", sizeKb: 350 },
      { id: "doc-010b", name: "Fleet Registration Documents.pdf", uploadedAt: "2026-03-21", uploadedBy: "Kigali Star Bus Ltd", sizeKb: 2700 },
    ],
  },
];
