import type { Workflow } from "@/types";

export const workflows: Workflow[] = [
  {
    id: "wfl-001",
    name: "New Licence Application — Telecom",
    description: "Standard multi-step review workflow for new telecom licence applications submitted via CLMS.",
    trigger: "license_application",
    status: "active",
    sector: "Telecom",
    createdBy: "Kagiso Mutabazi",
    createdAt: "2026-01-15",
    startedAt: "2026-03-10",
    relatedEntityId: "cls-001",
    steps: [
      { id: "s1-1", order: 1, name: "Document Verification", description: "Verify all submitted documents are complete and authentic.", assignedRole: "analyst", status: "completed", dueInDays: 3, completedAt: "2026-03-12", completedBy: "Jeannette Umurerwa" },
      { id: "s1-2", order: 2, name: "Technical Assessment", description: "Assess technical capacity and spectrum requirements.", assignedRole: "analyst", status: "completed", dueInDays: 5, completedAt: "2026-03-17", completedBy: "Olivier Hakizimana" },
      { id: "s1-3", order: 3, name: "Supervisor Review", description: "Supervisor sign-off on assessment findings.", assignedRole: "supervisor", status: "in_progress", dueInDays: 3 },
      { id: "s1-4", order: 4, name: "Final Approval", description: "Director approval and licence issuance.", assignedRole: "admin", status: "pending", dueInDays: 2 },
    ],
  },
  {
    id: "wfl-002",
    name: "Compliance Remediation — EUCL",
    description: "Remediation tracking workflow for EUCL network rollout target shortfall.",
    trigger: "compliance_due",
    status: "active",
    sector: "Energy",
    createdBy: "Jean-Claude Ndayisaba",
    createdAt: "2026-03-02",
    startedAt: "2026-03-05",
    relatedEntityId: "com-004",
    steps: [
      { id: "s2-1", order: 1, name: "Remediation Plan Review", description: "Review and accept the remediation plan submitted by EUCL.", assignedRole: "auditor", status: "completed", dueInDays: 5, completedAt: "2026-03-08", completedBy: "Jean-Claude Ndayisaba" },
      { id: "s2-2", order: 2, name: "Quarterly Progress Check", description: "First quarterly review of remediation milestones.", assignedRole: "auditor", status: "in_progress", dueInDays: 30 },
      { id: "s2-3", order: 3, name: "Second Progress Check", description: "Second quarterly review.", assignedRole: "auditor", status: "pending", dueInDays: 60 },
      { id: "s2-4", order: 4, name: "Final Compliance Sign-off", description: "Confirm full compliance achieved.", assignedRole: "supervisor", status: "pending", dueInDays: 5 },
    ],
  },
  {
    id: "wfl-003",
    name: "Fraud Investigation — SIM Box",
    description: "Investigation workflow for SIM box fraud case RURA-FRD-2026-0019.",
    trigger: "fraud_alert",
    status: "paused",
    sector: "Telecom",
    createdBy: "Olivier Hakizimana",
    createdAt: "2026-03-06",
    startedAt: "2026-03-06",
    relatedEntityId: "frd-001",
    steps: [
      { id: "s3-1", order: 1, name: "Initial Assessment", description: "Classify risk level and assign investigating officer.", assignedRole: "analyst", status: "completed", dueInDays: 1, completedAt: "2026-03-07", completedBy: "Olivier Hakizimana" },
      { id: "s3-2", order: 2, name: "Evidence Collection", description: "Gather call records and technical logs from MTN Rwanda.", assignedRole: "analyst", status: "in_progress", dueInDays: 10 },
      { id: "s3-3", order: 3, name: "Legal Review", description: "Legal team assessment for prosecution referral.", assignedRole: "supervisor", status: "pending", dueInDays: 7 },
      { id: "s3-4", order: 4, name: "Referral to RNP", description: "Refer confirmed case to Rwanda National Police.", assignedRole: "admin", status: "pending", dueInDays: 3 },
    ],
  },
  {
    id: "wfl-004",
    name: "Licence Renewal — WASAC",
    description: "Annual licence renewal workflow for WASAC Water Supply licence.",
    trigger: "renewal_due",
    status: "paused",
    sector: "Water",
    createdBy: "Kagiso Mutabazi",
    createdAt: "2026-02-20",
    startedAt: "2026-02-25",
    relatedEntityId: "lic-010",
    steps: [
      { id: "s4-1", order: 1, name: "Renewal Application Receipt", description: "Confirm receipt and completeness of renewal application.", assignedRole: "analyst", status: "completed", dueInDays: 2, completedAt: "2026-02-26", completedBy: "Amina Uwimana" },
      { id: "s4-2", order: 2, name: "Compliance Verification", description: "Confirm operator is in good compliance standing.", assignedRole: "auditor", status: "in_progress", dueInDays: 7 },
      { id: "s4-3", order: 3, name: "Fee Assessment", description: "Calculate and issue renewal fee invoice.", assignedRole: "analyst", status: "pending", dueInDays: 3 },
      { id: "s4-4", order: 4, name: "Licence Issue", description: "Issue renewed licence certificate.", assignedRole: "supervisor", status: "pending", dueInDays: 2 },
    ],
  },
  {
    id: "wfl-005",
    name: "Complaint Escalation — Capital Express",
    description: "Escalation workflow for unresolved tariff overcharge complaints against Capital Express.",
    trigger: "complaint_filed",
    status: "completed",
    sector: "Transport",
    createdBy: "Amina Uwimana",
    createdAt: "2026-01-15",
    startedAt: "2026-01-16",
    completedAt: "2026-02-28",
    relatedEntityId: "cmp-009",
    steps: [
      { id: "s5-1", order: 1, name: "Complaint Triage", description: "Classify and assign complaint.", assignedRole: "analyst", status: "completed", dueInDays: 1, completedAt: "2026-01-16", completedBy: "Amina Uwimana" },
      { id: "s5-2", order: 2, name: "Operator Response Request", description: "Issue formal response request to Capital Express.", assignedRole: "supervisor", status: "completed", dueInDays: 7, completedAt: "2026-01-23", completedBy: "Amina Uwimana" },
      { id: "s5-3", order: 3, name: "Mediation Hearing", description: "Conduct formal mediation between parties.", assignedRole: "supervisor", status: "completed", dueInDays: 14, completedAt: "2026-02-10", completedBy: "Amina Uwimana" },
      { id: "s5-4", order: 4, name: "Resolution & Notice", description: "Issue regulatory decision and notify parties.", assignedRole: "admin", status: "completed", dueInDays: 5, completedAt: "2026-02-28", completedBy: "Kagiso Mutabazi" },
    ],
  },
  {
    id: "wfl-006",
    name: "Spectrum Assignment — Airtel",
    description: "Workflow for spectrum reallocation request from Airtel Rwanda on 4G band expansion.",
    trigger: "license_application",
    status: "draft",
    sector: "Telecom",
    createdBy: "Kagiso Mutabazi",
    createdAt: "2026-03-20",
    steps: [
      { id: "s6-1", order: 1, name: "Application Intake", description: "Log spectrum assignment request and verify documentation.", assignedRole: "analyst", status: "pending", dueInDays: 2 },
      { id: "s6-2", order: 2, name: "Interference Assessment", description: "Technical analysis of spectrum availability and interference risk.", assignedRole: "analyst", status: "pending", dueInDays: 7 },
      { id: "s6-3", order: 3, name: "Fee Calculation", description: "Compute spectrum usage fees per RURA tariff schedule.", assignedRole: "analyst", status: "pending", dueInDays: 3 },
      { id: "s6-4", order: 4, name: "Director Sign-off", description: "Final approval for spectrum assignment.", assignedRole: "admin", status: "pending", dueInDays: 3 },
    ],
  },
  {
    id: "wfl-007",
    name: "Annual Compliance Audit — MTN Rwanda",
    description: "Annual QoS and consumer protection audit for MTN Rwanda.",
    trigger: "compliance_due",
    status: "completed",
    sector: "Telecom",
    createdBy: "Jean-Claude Ndayisaba",
    createdAt: "2025-12-01",
    startedAt: "2026-01-05",
    completedAt: "2026-01-20",
    relatedEntityId: "com-001",
    steps: [
      { id: "s7-1", order: 1, name: "Audit Scheduling", description: "Notify MTN Rwanda and set audit dates.", assignedRole: "auditor", status: "completed", dueInDays: 3, completedAt: "2026-01-07", completedBy: "Jean-Claude Ndayisaba" },
      { id: "s7-2", order: 2, name: "On-site Inspection", description: "Conduct on-site QoS measurement and data collection.", assignedRole: "auditor", status: "completed", dueInDays: 5, completedAt: "2026-01-14", completedBy: "Jean-Claude Ndayisaba" },
      { id: "s7-3", order: 3, name: "Report Drafting", description: "Draft audit findings report.", assignedRole: "auditor", status: "completed", dueInDays: 4, completedAt: "2026-01-18", completedBy: "Jean-Claude Ndayisaba" },
      { id: "s7-4", order: 4, name: "Close-out", description: "Issue final report and update compliance record.", assignedRole: "supervisor", status: "completed", dueInDays: 2, completedAt: "2026-01-20", completedBy: "Amina Uwimana" },
    ],
  },
  {
    id: "wfl-008",
    name: "Manual Review — Unlicensed ISP",
    description: "Manual investigation workflow for unlicensed ISP tip-off in Rubavu district.",
    trigger: "manual",
    status: "active",
    sector: "Telecom",
    createdBy: "Amina Uwimana",
    createdAt: "2025-12-15",
    startedAt: "2025-12-16",
    relatedEntityId: "frd-005",
    steps: [
      { id: "s8-1", order: 1, name: "Tip-off Verification", description: "Verify tip-off information and assess credibility.", assignedRole: "analyst", status: "completed", dueInDays: 2, completedAt: "2025-12-17", completedBy: "Amina Uwimana" },
      { id: "s8-2", order: 2, name: "Field Inspection", description: "Conduct unannounced field visit to Rubavu district.", assignedRole: "analyst", status: "completed", dueInDays: 14, completedAt: "2026-01-10", completedBy: "Amina Uwimana" },
      { id: "s8-3", order: 3, name: "Enforcement Action", description: "Issue cease-and-desist notice and fine calculation.", assignedRole: "supervisor", status: "in_progress", dueInDays: 7 },
      { id: "s8-4", order: 4, name: "Case Closure", description: "Confirm operator ceased unlicensed operations.", assignedRole: "auditor", status: "pending", dueInDays: 30 },
    ],
  },
];
