import type { License, LicenseTrendPoint } from "@/types";

// 12 Rwanda-relevant license records covering Telecom, Energy, Water, Transport
export const licenses: License[] = [
  {
    id: "lic-001",
    licenseNumber: "RURA-TLC-2021-001",
    operatorName: "MTN Rwanda Ltd",
    contactPerson: "Jean-Paul Habimana",
    contactEmail: "regulatory@mtn.rw",
    category: "Mobile Network Operator",
    sector: "Telecom",
    status: "active",
    province: "Kigali City",
    issuedAt: "2021-07-01",
    expiresAt: "2026-06-30",
    annualFeeRwf: 250_000_000,
    lastRenewalAt: "2024-07-01",
  },
  {
    id: "lic-002",
    licenseNumber: "RURA-TLC-2021-002",
    operatorName: "Airtel Rwanda Ltd",
    contactPerson: "Diane Mukamana",
    contactEmail: "regulatory@airtel.rw",
    category: "Mobile Network Operator",
    sector: "Telecom",
    status: "active",
    province: "Kigali City",
    issuedAt: "2021-07-01",
    expiresAt: "2026-06-30",
    annualFeeRwf: 200_000_000,
    lastRenewalAt: "2024-07-01",
  },
  {
    id: "lic-003",
    licenseNumber: "RURA-TLC-2022-007",
    operatorName: "Liquid Intelligent Technologies Rwanda",
    contactPerson: "Emmanuel Niyonsaba",
    contactEmail: "licensing@liquid.rw",
    category: "Internet Service Provider",
    sector: "Telecom",
    status: "active",
    province: "Kigali City",
    issuedAt: "2022-02-14",
    expiresAt: "2025-02-13",
    annualFeeRwf: 45_000_000,
  },
  {
    id: "lic-004",
    licenseNumber: "RURA-TLC-2023-015",
    operatorName: "IKE Group Ltd",
    contactPerson: "Solange Uwamariya",
    contactEmail: "compliance@ikegroup.rw",
    category: "Fixed Network Operator",
    sector: "Telecom",
    status: "pending",
    province: "Northern Province",
    issuedAt: "2023-11-20",
    expiresAt: "2028-11-19",
    annualFeeRwf: 30_000_000,
  },
  {
    id: "lic-005",
    licenseNumber: "RURA-TLC-2019-003",
    operatorName: "Brintel Ltd",
    contactPerson: "Patrick Nzeyimana",
    contactEmail: "admin@brintel.rw",
    category: "Internet Service Provider",
    sector: "Telecom",
    status: "expired",
    province: "Western Province",
    issuedAt: "2019-03-01",
    expiresAt: "2024-02-28",
    annualFeeRwf: 12_000_000,
    lastRenewalAt: "2022-03-01",
  },
  {
    id: "lic-006",
    licenseNumber: "RURA-TLC-2024-022",
    operatorName: "Terracom Rwanda",
    contactPerson: "Claudine Nyirabeza",
    contactEmail: "legal@terracom.rw",
    category: "Virtual Network Operator",
    sector: "Telecom",
    status: "active",
    province: "Southern Province",
    issuedAt: "2024-01-10",
    expiresAt: "2029-01-09",
    annualFeeRwf: 18_000_000,
  },
  {
    id: "lic-007",
    licenseNumber: "RURA-ENE-2020-001",
    operatorName: "Rwanda Energy Group (EUCL)",
    contactPerson: "Théogène Rutagengwa",
    contactEmail: "regulatory@reg.rw",
    category: "Electricity Distribution",
    sector: "Energy",
    status: "active",
    province: "Kigali City",
    issuedAt: "2020-06-01",
    expiresAt: "2025-05-31",
    annualFeeRwf: 85_000_000,
    lastRenewalAt: "2023-06-01",
  },
  {
    id: "lic-008",
    licenseNumber: "RURA-ENE-2021-004",
    operatorName: "EDCL – Energy Development Corp.",
    contactPerson: "Alexis Ngendahimana",
    contactEmail: "compliance@edcl.rw",
    category: "Power Generation",
    sector: "Energy",
    status: "active",
    province: "Northern Province",
    issuedAt: "2021-09-15",
    expiresAt: "2026-09-14",
    annualFeeRwf: 60_000_000,
  },
  {
    id: "lic-009",
    licenseNumber: "RURA-ENE-2022-009",
    operatorName: "Ruzizi Thermal Power Ltd",
    contactPerson: "Félicien Bizimungu",
    contactEmail: "ruzizi@thermal.rw",
    category: "Power Generation",
    sector: "Energy",
    status: "suspended",
    province: "Western Province",
    issuedAt: "2022-04-01",
    expiresAt: "2027-03-31",
    annualFeeRwf: 40_000_000,
  },
  {
    id: "lic-010",
    licenseNumber: "RURA-WAT-2020-001",
    operatorName: "WASAC – Water & Sanitation Corp.",
    contactPerson: "Immaculée Nyiraneza",
    contactEmail: "regulatory@wasac.rw",
    category: "Water Supply",
    sector: "Water",
    status: "active",
    province: "Kigali City",
    issuedAt: "2020-01-01",
    expiresAt: "2025-12-31",
    annualFeeRwf: 55_000_000,
    lastRenewalAt: "2023-01-01",
  },
  {
    id: "lic-011",
    licenseNumber: "RURA-TRN-2023-001",
    operatorName: "Volcano Express Ltd",
    contactPerson: "Richard Mugabo",
    contactEmail: "ops@volcanoexpress.rw",
    category: "Road Transport Operator",
    sector: "Transport",
    status: "active",
    province: "Southern Province",
    issuedAt: "2023-06-01",
    expiresAt: "2026-05-31",
    annualFeeRwf: 8_000_000,
  },
  {
    id: "lic-012",
    licenseNumber: "RURA-TRN-2022-004",
    operatorName: "Capital Express Transport",
    contactPerson: "Vestine Uwamungu",
    contactEmail: "licensing@capitalexpress.rw",
    category: "Freight & Logistics",
    sector: "Transport",
    status: "active",
    province: "Eastern Province",
    issuedAt: "2022-08-20",
    expiresAt: "2025-08-19",
    annualFeeRwf: 6_500_000,
  },
];

export const licenseTrend: LicenseTrendPoint[] = [
  { month: "Oct", issued: 12, revoked: 1, expired: 2 },
  { month: "Nov", issued: 15, revoked: 2, expired: 1 },
  { month: "Dec", issued: 8,  revoked: 0, expired: 3 },
  { month: "Jan", issued: 18, revoked: 1, expired: 2 },
  { month: "Feb", issued: 14, revoked: 2, expired: 1 },
  { month: "Mar", issued: 21, revoked: 1, expired: 0 },
];
