import type { FraudCase } from "@/types";

export const fraudCases: FraudCase[] = [
  {
    id: "frd-001",
    caseNumber: "RURA-FRD-2026-0019",
    description: "SIM box fraud operation intercepting international calls to evade termination fees",
    indicatorType: "SIM Box Fraud",
    reportedBy: "MTN Rwanda Fraud Unit",
    operatorInvolved: "Unknown third party",
    sector: "Telecom",
    riskLevel: "critical",
    status: "investigating",
    reportedAt: "2026-03-05",
    estimatedLossRwf: 180_000_000,
    investigatingOfficer: "Olivier Hakizimana",
  },
  {
    id: "frd-002",
    caseNumber: "RURA-FRD-2026-0015",
    description: "Ghost customer registrations used to inflate subscriber count in licence compliance reporting",
    indicatorType: "Ghost Customer Registrations",
    reportedBy: "Internal RURA Analytics",
    operatorInvolved: "Brintel Ltd",
    sector: "Telecom",
    riskLevel: "high",
    status: "open",
    reportedAt: "2026-02-22",
    estimatedLossRwf: 0,
    investigatingOfficer: "Amina Uwimana",
  },
  {
    id: "frd-003",
    caseNumber: "RURA-FRD-2026-0011",
    description: "Electricity meter tampering detected at commercial premises in Kigali",
    indicatorType: "Meter Tampering",
    reportedBy: "EUCL Field Inspection Team",
    operatorInvolved: "Rwanda Energy Group (EUCL)",
    sector: "Energy",
    riskLevel: "high",
    status: "confirmed",
    reportedAt: "2026-02-10",
    estimatedLossRwf: 42_000_000,
    investigatingOfficer: "Jeannette Umurerwa",
  },
  {
    id: "frd-004",
    caseNumber: "RURA-FRD-2026-0007",
    description: "Revenue underreporting by transport operator to reduce licence fee assessment",
    indicatorType: "Revenue Underreporting",
    reportedBy: "RURA Finance Division",
    operatorInvolved: "Capital Express Transport",
    sector: "Transport",
    riskLevel: "medium",
    status: "referred",
    reportedAt: "2026-01-30",
    estimatedLossRwf: 9_500_000,
    investigatingOfficer: "Olivier Hakizimana",
  },
  {
    id: "frd-005",
    caseNumber: "RURA-FRD-2025-0098",
    description: "Unlicensed ISP operating in Rubavu district without RURA authorisation",
    indicatorType: "Unlicensed Operation",
    reportedBy: "Public Tip-Off",
    operatorInvolved: "Unknown — under investigation",
    sector: "Telecom",
    riskLevel: "medium",
    status: "investigating",
    reportedAt: "2025-12-14",
    estimatedLossRwf: 0,
    investigatingOfficer: "Amina Uwimana",
  },
  {
    id: "frd-006",
    caseNumber: "RURA-FRD-2025-0081",
    description: "Tariff manipulation — operator applying non-approved tariff schedule for rural customers",
    indicatorType: "Tariff Manipulation",
    reportedBy: "Consumer Complaints Data",
    operatorInvolved: "Terracom Rwanda",
    sector: "Telecom",
    riskLevel: "low",
    status: "dismissed",
    reportedAt: "2025-10-05",
    estimatedLossRwf: 2_400_000,
  },
  {
    id: "frd-007",
    caseNumber: "RURA-FRD-2026-0022",
    description: "Spectrum interference detected on 4G band causing service degradation for adjacent operators",
    indicatorType: "Spectrum Interference",
    reportedBy: "Airtel Rwanda Technical Team",
    operatorInvolved: "Liquid Intelligent Technologies Rwanda",
    sector: "Telecom",
    riskLevel: "critical",
    status: "open",
    reportedAt: "2026-03-18",
    estimatedLossRwf: 0,
    investigatingOfficer: "Théogène Rutagengwa",
  },
  {
    id: "frd-008",
    caseNumber: "RURA-FRD-2026-0014",
    description: "Duplicate water connection applications submitted under different company names to obtain multiple subsidised connections",
    indicatorType: "Duplicate Applications",
    reportedBy: "WASAC Licensing Office",
    operatorInvolved: "Unknown — multiple entities",
    sector: "Water",
    riskLevel: "high",
    status: "investigating",
    reportedAt: "2026-02-17",
    estimatedLossRwf: 18_700_000,
    investigatingOfficer: "Jeannette Umurerwa",
  },
  {
    id: "frd-009",
    caseNumber: "RURA-FRD-2026-0009",
    description: "Identity misrepresentation — company directors listed on licence differ from actual controlling shareholders",
    indicatorType: "Identity Misrepresentation",
    reportedBy: "RURA Legal Department",
    operatorInvolved: "Volcano Express Ltd",
    sector: "Transport",
    riskLevel: "medium",
    status: "confirmed",
    reportedAt: "2026-01-28",
    estimatedLossRwf: 0,
    investigatingOfficer: "Kagiso Mutabazi",
  },
  {
    id: "frd-010",
    caseNumber: "RURA-FRD-2025-0073",
    description: "Unusual billing pattern — water utility issuing inflated invoices to commercial customers during peak season",
    indicatorType: "Unusual Billing Pattern",
    reportedBy: "Consumer Complaints Data",
    operatorInvolved: "WASAC – Water & Sanitation Corp.",
    sector: "Water",
    riskLevel: "low",
    status: "dismissed",
    reportedAt: "2025-09-12",
    estimatedLossRwf: 4_100_000,
    investigatingOfficer: "Kagiso Mutabazi",
  },
];
