import type { Report } from "@/types";

export const reports: Report[] = [
  {
    id: "rpt-001",
    title: "Q1 2026 Telecom Regulatory Report",
    type: "quarterly",
    sector: "Telecom",
    status: "draft",
    format: "pdf",
    createdBy: "Jean-Claude Ndayisaba",
    createdAt: "2026-03-20",
    period: "Jan – Mar 2026",
    sizeKb: 3850,
  },
  {
    id: "rpt-002",
    title: "Annual Compliance Summary 2025",
    type: "annual",
    sector: "All Sectors",
    status: "published",
    format: "pdf",
    createdBy: "Kagiso Mutabazi",
    createdAt: "2026-02-01",
    publishedAt: "2026-02-15",
    period: "Jan – Dec 2025",
    sizeKb: 12400,
    downloadUrl: "#",
  },
  {
    id: "rpt-003",
    title: "Q4 2025 Telecom Sector Report",
    type: "quarterly",
    sector: "Telecom",
    status: "published",
    format: "pdf",
    createdBy: "Jean-Claude Ndayisaba",
    createdAt: "2026-01-20",
    publishedAt: "2026-01-31",
    period: "Oct – Dec 2025",
    sizeKb: 4200,
    downloadUrl: "#",
  },
  {
    id: "rpt-004",
    title: "Monthly Complaints Report — February 2026",
    type: "monthly",
    sector: "All Sectors",
    status: "published",
    format: "xlsx",
    createdBy: "Amina Uwimana",
    createdAt: "2026-03-05",
    publishedAt: "2026-03-05",
    period: "Feb 2026",
    sizeKb: 890,
    downloadUrl: "#",
  },
  {
    id: "rpt-005",
    title: "Energy Sector Compliance Review — H2 2025",
    type: "ad_hoc",
    sector: "Energy",
    status: "published",
    format: "pdf",
    createdBy: "Jean-Claude Ndayisaba",
    createdAt: "2026-01-10",
    publishedAt: "2026-01-18",
    period: "Jul – Dec 2025",
    sizeKb: 5600,
    downloadUrl: "#",
  },
  {
    id: "rpt-006",
    title: "Fraud & Anomaly Detection Summary — Q4 2025",
    type: "quarterly",
    sector: "All Sectors",
    status: "archived",
    format: "pdf",
    createdBy: "Olivier Hakizimana",
    createdAt: "2026-01-05",
    publishedAt: "2026-01-08",
    period: "Oct – Dec 2025",
    sizeKb: 2900,
    downloadUrl: "#",
  },
  {
    id: "rpt-007",
    title: "Water Sector Tariff Review Analysis",
    type: "ad_hoc",
    sector: "Water",
    status: "published",
    format: "pdf",
    createdBy: "Amina Uwimana",
    createdAt: "2026-02-28",
    publishedAt: "2026-03-03",
    period: "2026",
    sizeKb: 1750,
    downloadUrl: "#",
  },
  {
    id: "rpt-008",
    title: "Monthly Complaints Report — March 2026",
    type: "monthly",
    sector: "All Sectors",
    status: "draft",
    format: "xlsx",
    createdBy: "Amina Uwimana",
    createdAt: "2026-03-22",
    period: "Mar 2026",
    sizeKb: 640,
  },
  {
    id: "rpt-009",
    title: "Transport Operator Licence Status — 2025",
    type: "annual",
    sector: "Transport",
    status: "archived",
    format: "csv",
    createdBy: "Jeannette Umurerwa",
    createdAt: "2026-01-15",
    publishedAt: "2026-01-15",
    period: "Jan – Dec 2025",
    sizeKb: 380,
    downloadUrl: "#",
  },
  {
    id: "rpt-010",
    title: "SIM Box Fraud Investigation — Preliminary Findings",
    type: "ad_hoc",
    sector: "Telecom",
    status: "draft",
    format: "pdf",
    createdBy: "Olivier Hakizimana",
    createdAt: "2026-03-18",
    period: "Mar 2026",
    sizeKb: 1120,
  },
];
