import type { ActivityItem } from "@/types";

export const recentActivity: ActivityItem[] = [
  {
    id: "act-001",
    type: "license_issued",
    description: "License RURA-TLC-2026-031 issued to Kigali Online Ltd",
    actor: "Jean-Claude Ndayisaba",
    module: "Licenses",
    timestamp: "2026-03-22T09:15:00Z",
    entityId: "lic-031",
  },
  {
    id: "act-002",
    type: "complaint_filed",
    description: "Complaint RURA-CMP-2026-0042 filed against MTN Rwanda — SIM swap fraud",
    actor: "System",
    module: "Complaints",
    timestamp: "2026-03-22T08:40:00Z",
    entityId: "cmp-042",
  },
  {
    id: "act-003",
    type: "fraud_flagged",
    description: "SIM box operation detected — Kigali CBD, estimated loss RWF 12M",
    actor: "System",
    module: "Fraud",
    timestamp: "2026-03-22T07:55:00Z",
  },
  {
    id: "act-004",
    type: "compliance_breach",
    description: "Ruzizi Thermal Power missed emissions remediation deadline",
    actor: "Jeannette Umurerwa",
    module: "Compliance",
    timestamp: "2026-03-21T16:30:00Z",
    entityId: "com-003",
  },
  {
    id: "act-005",
    type: "workflow_triggered",
    description: "License renewal workflow started for WASAC – Water & Sanitation",
    actor: "System",
    module: "Workflows",
    timestamp: "2026-03-21T14:05:00Z",
    entityId: "lic-010",
  },
  {
    id: "act-006",
    type: "complaint_resolved",
    description: "Complaint RURA-CMP-2026-0030 resolved — WASAC Gicumbi water supply restored",
    actor: "Amina Uwimana",
    module: "Complaints",
    timestamp: "2026-03-21T11:20:00Z",
    entityId: "cmp-030",
  },
  {
    id: "act-007",
    type: "audit_completed",
    description: "Q1 2026 compliance audit completed for Airtel Rwanda Ltd",
    actor: "Amina Uwimana",
    module: "Compliance",
    timestamp: "2026-03-20T16:45:00Z",
    entityId: "com-002",
  },
  {
    id: "act-008",
    type: "alert_raised",
    description: "License expiry alert: Brintel Ltd — 0 days remaining",
    actor: "System",
    module: "Alerts",
    timestamp: "2026-03-20T09:00:00Z",
    entityId: "lic-005",
  },
  {
    id: "act-009",
    type: "license_suspended",
    description: "License RURA-ENE-2022-009 suspended — Ruzizi Thermal Power Ltd",
    actor: "Kagiso Mutabazi",
    module: "Licenses",
    timestamp: "2026-03-19T14:30:00Z",
    entityId: "lic-009",
  },
  {
    id: "act-010",
    type: "report_published",
    description: "Q4 2025 Telecom Sector Report published and available for download",
    actor: "Théogène Rutagengwa",
    module: "Reports",
    timestamp: "2026-03-18T10:00:00Z",
  },
];
