import type { AuditLogEntry } from "@/types";

export const auditLog: AuditLogEntry[] = [
  {
    id: "aud-001",
    userId: "usr-001",
    userName: "Kagiso Mutabazi",
    action: "approve",
    module: "Licenses",
    entityId: "lic-001",
    entityLabel: "MTN Rwanda Ltd — Mobile Network Operator",
    ipAddress: "196.12.34.5",
    userAgent: "Chrome 122 / Windows",
    timestamp: "2026-03-22T08:14:23Z",
    changes: {
      status: { before: "pending", after: "active" },
    },
  },
  {
    id: "aud-002",
    userId: "usr-002",
    userName: "Amina Uwimana",
    action: "update",
    module: "Complaints",
    entityId: "cmp-007",
    entityLabel: "CMP-2026-0018 — Billing Dispute",
    ipAddress: "196.12.34.8",
    userAgent: "Firefox 123 / Windows",
    timestamp: "2026-03-22T07:58:44Z",
    changes: {
      status: { before: "open", after: "under_review" },
      assignedTo: { before: "Unassigned", after: "Amina Uwimana" },
    },
  },
  {
    id: "aud-003",
    userId: "usr-005",
    userName: "Olivier Hakizimana",
    action: "create",
    module: "Fraud",
    entityId: "frd-007",
    entityLabel: "RURA-FRD-2026-0022 — Spectrum Interference",
    ipAddress: "196.12.34.11",
    userAgent: "Chrome 122 / macOS",
    timestamp: "2026-03-21T16:45:10Z",
  },
  {
    id: "aud-004",
    userId: "usr-003",
    userName: "Jean-Claude Ndayisaba",
    action: "update",
    module: "Compliance",
    entityId: "com-004",
    entityLabel: "EUCL — Network Rollout Target",
    ipAddress: "196.12.34.3",
    userAgent: "Chrome 122 / Windows",
    timestamp: "2026-03-21T15:20:00Z",
    changes: {
      status: { before: "non_compliant", after: "remediation" },
    },
  },
  {
    id: "aud-005",
    userId: "usr-001",
    userName: "Kagiso Mutabazi",
    action: "export",
    module: "Reports",
    entityId: "rpt-003",
    entityLabel: "Q4 2025 Telecom Sector Report",
    ipAddress: "196.12.34.5",
    userAgent: "Chrome 122 / Windows",
    timestamp: "2026-03-21T14:02:55Z",
  },
  {
    id: "aud-006",
    userId: "usr-004",
    userName: "Jeannette Umurerwa",
    action: "suspend",
    module: "Licenses",
    entityId: "lic-006",
    entityLabel: "Terracom Rwanda — Fixed Network Operator",
    ipAddress: "196.12.34.14",
    userAgent: "Edge 121 / Windows",
    timestamp: "2026-03-20T11:35:18Z",
    changes: {
      status: { before: "active", after: "suspended" },
    },
  },
  {
    id: "aud-007",
    userId: "usr-002",
    userName: "Amina Uwimana",
    action: "reject",
    module: "CLMS",
    entityId: "cls-005",
    entityLabel: "CLMS-2026-0031 — Tariff Review Application",
    ipAddress: "196.12.34.8",
    userAgent: "Firefox 123 / Windows",
    timestamp: "2026-03-20T10:14:30Z",
    changes: {
      status: { before: "under_review", after: "rejected" },
    },
  },
  {
    id: "aud-008",
    userId: "usr-001",
    userName: "Kagiso Mutabazi",
    action: "permission_change",
    module: "Users",
    entityId: "usr-006",
    entityLabel: "Cécile Ingabire",
    ipAddress: "196.12.34.5",
    userAgent: "Chrome 122 / Windows",
    timestamp: "2026-03-19T09:05:00Z",
    changes: {
      role: { before: "viewer", after: "analyst" },
    },
  },
  {
    id: "aud-009",
    userId: "usr-003",
    userName: "Jean-Claude Ndayisaba",
    action: "login",
    module: "System",
    entityId: "usr-003",
    entityLabel: "Jean-Claude Ndayisaba",
    ipAddress: "196.12.34.3",
    userAgent: "Chrome 122 / Windows",
    timestamp: "2026-03-19T08:00:12Z",
  },
  {
    id: "aud-010",
    userId: "usr-005",
    userName: "Olivier Hakizimana",
    action: "update",
    module: "Workflows",
    entityId: "wfl-003",
    entityLabel: "Fraud Investigation Workflow — frd-001",
    ipAddress: "196.12.34.11",
    userAgent: "Chrome 122 / macOS",
    timestamp: "2026-03-18T15:50:40Z",
    changes: {
      status: { before: "active", after: "paused" },
    },
  },
  {
    id: "aud-011",
    userId: "usr-004",
    userName: "Jeannette Umurerwa",
    action: "create",
    module: "Compliance",
    entityId: "com-010",
    entityLabel: "EDCL — Financial Reporting",
    ipAddress: "196.12.34.14",
    userAgent: "Edge 121 / Windows",
    timestamp: "2026-03-17T13:22:05Z",
  },
  {
    id: "aud-012",
    userId: "usr-001",
    userName: "Kagiso Mutabazi",
    action: "delete",
    module: "Alerts",
    entityId: "alt-008",
    entityLabel: "Alert — Workflow Stalled (wfl-002)",
    ipAddress: "196.12.34.5",
    userAgent: "Chrome 122 / Windows",
    timestamp: "2026-03-17T09:30:00Z",
  },
];
